FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# bucketlist

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [https://buckapi.herokuapp.com/auth/register]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New USER [POST]

It takes a JSON object containing a username, email and password.

+ Request (application/json)

        {
            "username": "Mbaka",
            "email" : "sarah@gmail.com"
            "password": "123456789"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Content-Type:application/json

    + Body

        {
            "message": "User Registration success!"
        }