FORMAT: 1A
HOST: https://buckapi.herokuapp.com

# Bucketlist
Bucketlist app is an application that allows users to record and share things they want to achieve or experience before reaching a certain age meeting the needs of keeping track of their dreams and goals.

## Group Authentication 

## Registration [/auth/register]

### Register a User  [POST]

It takes a JSON object containing a username, email and password.

Password cannot be less that  characters.

Username must be Unique.


+ Request (application/json)

        {
            "username": "Mbaka",
            "email" : "sarah@gmail.com"
            "password": "123456789"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Content-Type:application/json

    + Body

        {
            "message": "User Registration success!"
        }
